name: scalapay_ui
description: "Scalapay design system: foundations, theme and atomic widgets."
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  assets:
    - assets/icons/
